" enable all features
set nocompatible

filetype on
filetype indent on
filetype plugin on

" show line numbers
set number

" enable syntax highlighting
syntax on
set background=dark

" don't use fancy symbols in statusline
let g:Powerline_symbols = "compatible"
