" enable all features
set nocompatible

" initialize pathogen
call pathogen#infect()
call pathogen#helptags()

filetype on
filetype indent on
filetype plugin on

" show line numbers
set number

" enable syntax highlighting
syntax on
set background=dark
set t_Co=256

" always show statusbar
set laststatus=2

" don't use fancy symbols in statusline
let g:Powerline_symbols = "compatible"
